[D2] Icon 구현 및 Preview 작성
mash-up-kr/weQuiz-iOS pull request #15
Opened 2023-05-29 05:58 UTC by szzang-kr

# 개요
- 🔗  이슈링크 : #8 

# 변경사항

## 작업 내용

* DesignSystem에 앱 전체에서 사용될 Icon 등록 및 Image의 Extension으로 사용할 수 있도록 기능 구현
* 아래와 같이 사용할 수 있습니다.
```swift 
import DesignSystemKit

Image.icon( {아이콘 namespace} )

Image.icon(Icon.Chevron.upBig)
Image.icon(Icon.Chevron.upMedium)

Image.icon(Icon.Checkmark.trueFill24)
Image.icon(Icon.Checkmark.falseLine20)
```

### 스크린샷

스크린샷 1|스크린샷2|스크린샷3
---|---|---
![Simulator Screenshot - iPhone 14 Pro - 2023-05-29 at 14 27 55](https://github.com/mash-up-kr/weQuiz-iOS/assets/39300449/e2644afb-fbc2-45ed-912d-f0dc058e97b8)|![Simulator Screenshot - iPhone 14 Pro - 2023-05-29 at 14 27 59](https://github.com/mash-up-kr/weQuiz-iOS/assets/39300449/cdfe5552-b3da-49f1-b166-963945f6af41)|![Simulator Screenshot - iPhone 14 Pro - 2023-05-29 at 14 28 03](https://github.com/mash-up-kr/weQuiz-iOS/assets/39300449/af5bb655-5645-48b3-b5d4-f07600e0a299)

2023-06-02 09:23 UTC, sohy1018 commented
```
Image.icon(.Chevron.upBig)
Image.icon(Icon.Chevron.upMedium)

Image.icon(.Checkmark.trueFill24)
Image.icon(.Checkmark.falseLine20)
```

`icon`이라는 단어가 중복되니 이런 식으로 사용할 수 있으면 좋겠습니다~

2023-06-02 09:25 UTC, sohy1018 requested changes
```
Image.icon(.Chevron.upBig)
Image.icon(Icon.Chevron.upMedium)

Image.icon(.Checkmark.trueFill24)
Image.icon(.Checkmark.falseLine20)
```

`icon`이라는 단어가 중복되니 이런 식으로 사용할 수 있으면 좋겠습니다~

2023-06-03 05:54 UTC, szzang-kr commented
> ```
> Image.icon(.Chevron.upBig)
> Image.icon(Icon.Chevron.upMedium)
> 
> Image.icon(.Checkmark.trueFill24)
> Image.icon(.Checkmark.falseLine20)
> ```
> 
> 
>      
>   
> 
> `icon`이라는 단어가 중복되니 이런 식으로 사용할 수 있으면 좋겠습니다~

https://github.com/mash-up-kr/weQuiz-iOS/pull/15/commits/f6aab164dfe0f408e4b1e2e9cc00447c7f7f2fef 커밋에서 반영완료!

2023-06-03 06:28 UTC, sohy1018 approved these changes

2023-06-03 06:30 UTC, cws653 approved these changes

2023-06-03 06:33 UTC, merged