[DA] WQButton 구현 및 Preview 작성
mash-up-kr/weQuiz-iOS pull request #19
Opened 2023-06-10 03:50 UTC by szzang-kr

# 개요
- 🔗  이슈링크 : #8 

# 변경사항

## 작업 내용

* 공통으로 사용되는 버튼 Component를 작성하였습니다.
* 버튼의 색상은 Color가 확정된 후 Color 변경사항 반영 PR에서 적용할 예정입니다.
* 아래와 같은 방식으로 사용 가능합니다.
```swift

/// Radius가 있는 full size button
WQButton(
  style: .one(
      .init(
          title: "버튼",
          action: {
              print("버튼이 눌렸습니다")
          }
      )
  )
)

/// Radius가 없는 full size button
WQButton(
  style: .full(
      .init(
          title: "버튼",
          action: {
              print("버튼이 눌렸습니다")
          }
      )
  )
)

/// Radius가 있는 one button이 두개 존재하는 button
WQButton(
  style: .two(
      .init(
          titles: ("왼쪽버튼", "오른쪽버튼"),
          leftAction: {
              print("왼쪽버튼이 눌렸습니다")
          },
          rightAction: {
              print("오른쪽버튼이 눌렸습니다")
          }
      )
  )
)

```

### 스크린샷

<img src="https://github.com/mash-up-kr/weQuiz-iOS/assets/39300449/e1b0648c-f59d-4078-a9b2-5298f6410ac3" width="414" height="896">

2023-06-11 05:56 UTC, cws653 approved these changes, later dismissed

2023-06-17 05:05 UTC, sohy1018 requested changes
버튼 스타일 이름을 one, two 보다 이름만으로 어떤 타입인지 알 수 있게 지으면 좋을 것 같아요!!!
ex ) radiusFull , radiusFullTwo ...

2023-06-17 06:43 UTC, szzang-kr commented
> 버튼 스타일 이름을 one, two 보다 이름만으로 어떤 타입인지 알 수 있게 지으면 좋을 것 같아요!!!
> ex ) radiusFull , radiusFullTwo ...

https://github.com/mash-up-kr/weQuiz-iOS/pull/19/commits/e1c2f076df9d0ebba1ba7a00584fc5f71bca1dbd 커밋에서 반영 !

2023-06-17 06:45 UTC, sohy1018 approved these changes

2023-06-17 06:45 UTC, merged