:sparkles: Home뷰 기본 틀 구현 (#9, #10, #11, #12)
mash-up-kr/weQuiz-iOS pull request #26
Opened 2023-06-11 08:19 UTC by cws653

# 개요
- 현재 디자인 미확정 및 Component 미확정에 따라 향후 디테일하게 수정 예정
- Home, 친구랭킹 리스트, 문제리스트, 문제만들기 페이지 구현
- 🔗  이슈링크 : #9 #10 #11 #12 

# 작업 내용

1. Home 뷰 구현 : 하이라키뷰와 연결 완료
2. 친구랭킹 리스트 디테일뷰 구현
3. 문제리스트 구현
4. 문제만들기 페이지 구현|

2023-06-17 05:21 UTC, sohy1018 commented on Projects/Home/Targets/HomeUI/Sources/View/Home.swift
> +    var questionExpainView: some View {
ExpainView가 뭔가욤 ?? 오타일까요 ??

2023-06-17 05:57 UTC, szzang-kr requested changes

2023-06-17 05:57 UTC, szzang-kr commented on Projects/Home/Targets/HomeUI/Sources/View/FriendsList.swift
> +//}
사용하지 않는 코드는 삭제해주세요 :)

2023-06-17 05:57 UTC, szzang-kr commented on Projects/Home/Targets/HomeUI/Sources/View/Home.swift
> +//            .navigationTitle("HOME")
사용하지 않는 코드는 삭제해주세요 :)

2023-06-17 05:57 UTC, szzang-kr commented on Projects/Home/Targets/HomeUI/Sources/View/QuestionDetail.swift
> +//}
사용하지 않는 코드는 삭제해주세요 :)

2023-06-17 05:57 UTC, szzang-kr commented on Projects/Home/Targets/HomeUI/Sources/ViewModel/HomeViewModel.swift
> +//        self.friendsRank = []
사용하지 않는 코드는 삭제해주세요 :)

2023-06-17 05:57 UTC, szzang-kr commented on Projects/Home/Targets/HomeUI/Sources/View/QuestionGroupList.swift
> +//}
사용하지 않는 코드는 삭제해주세요 :)

2023-06-17 05:57 UTC, szzang-kr commented on Projects/Home/Targets/HomeUI/Sources/View/QuestionDetail.swift
> +struct questionsList: View {
해당 파일에서만 사용되는 View라면 private을 사용해서 외부의 불필요한 접근을 막을 수 있습니다

2023-06-17 05:57 UTC, szzang-kr commented on Projects/Home/Targets/HomeUI/Sources/View/QuestionDetailRow.swift
> +//}
사용하지 않는 코드는 삭제해주세요 :)

2023-06-25 05:59 UTC, cws653 commented on Projects/Home/Targets/HomeUI/Sources/View/Home.swift
> +    var questionExpainView: some View {
옙 오타입니다. ExplainView를 적으려고 했었습니다. 오타 수정하도록 하겠습니다!

2023-06-25 05:59 UTC, cws653 commented on Projects/Home/Targets/HomeUI/Sources/View/QuestionDetail.swift
> +struct questionsList: View {
옙 알겠습니다. 접근제한자를 통해서 외부에서 접근이 가능한 것인지 아닌지 명확하게 구분할 수 있도록 처리해놓겠습니다!

2023-06-25 05:59 UTC, cws653 commented on Projects/Home/Targets/HomeUI/Sources/View/QuestionDetail.swift
> +//}
옙 사용하지 않는 코드는 삭제하도록 하겠습니다!

2023-06-25 05:59 UTC, cws653 commented on Projects/Home/Targets/HomeUI/Sources/View/FriendsList.swift
> +//}
옙 사용하지 않는 코드는 삭제하도록 하겠습니다!

2023-06-25 05:59 UTC, cws653 commented on Projects/Home/Targets/HomeUI/Sources/View/QuestionDetailRow.swift
> +//}
옙 사용하지 않는 코드는 삭제하도록 하겠습니다!

2023-06-25 05:59 UTC, cws653 commented on Projects/Home/Targets/HomeUI/Sources/ViewModel/HomeViewModel.swift
> +//        self.friendsRank = []
옙 사용하지 않는 코드는 삭제하도록 하겠습니다!

2023-06-28 13:36 UTC, szzang-kr approved these changes

2023-06-28 13:50 UTC, dittoo8 approved these changes

2023-06-28 13:51 UTC, merged