QUIZ - 문제 만들기 페이지 View 구현  #14
mash-up-kr/weQuiz-iOS pull request #35
Opened 2023-06-23 15:52 UTC by dittoo8

# 개요
- 🔗  이슈링크 : #14 

# 변경사항

## 작업 내용
- 문제만들기 뷰 UI 구현
- 문제 입력 List UI 구현
- 답변 입력 뷰 UI 구현
- 질문 추가 기능 구현
- 순서 편집 기능 구현

기본 UI 업데이트 후 상세 UI 작업 예정입니다.

### 스크린샷
<img width="410" alt="스크린샷 2023-06-24 오전 12 49 11" src="https://github.com/mash-up-kr/weQuiz-iOS/assets/37571027/53602b1a-9302-4a44-804a-963f31c97f10">

2023-06-24 08:00 UTC, szzang-kr requested changes
수고했습니다 👍 

body 안에 모든 뷰를 작성하는것 보다 뷰 구조를 잘 나누어 뷰를 구성한다면 가독성을 더 보완할 수 있습니다 :)

2023-06-24 08:00 UTC, szzang-kr commented on Projects/Quiz/Targets/QuizUI/Sources/MakeQuizView.swift
> +//}
preview를 사용하지 않는다면 삭제하는편이 좋을 것 같아요 :)

2023-06-26 14:04 UTC, AhnSangHee approved these changes
LGTM🕶️

2023-06-26 14:04 UTC, szzang-kr approved these changes

2023-06-26 14:05 UTC, merged