💡  Home - QuestionDetailView Flip Card 적용
mash-up-kr/weQuiz-iOS pull request #66
Opened 2023-07-16 07:21 UTC by cws653

# 개요
- 🔗  이슈링크 : #64 

## 작업 내용

- Home DetailView AnswerList Cell 클릭시 Flip 되도록 기능 구현

### 미리보기

작업 후

Simulator Screen Recording - iPhone 14 Pro - 2023-07-16 at 16.19.25.mp4

2023-07-16 07:25 UTC, szzang-kr requested changes

2023-07-16 07:25 UTC, szzang-kr commented on Projects/Home/Targets/HomeUI/Sources/View/TestFlipView.swift
> +//        .cardFilp(isFaceUp: isFaceUp, axis: axis)
:)

2023-07-16 07:25 UTC, szzang-kr commented on Projects/Home/Targets/HomeUI/Sources/View/TestFlipView.swift
> +}
:)

2023-07-16 07:25 UTC, szzang-kr commented on Projects/Home/Targets/HomeUI/Sources/View/AnswerPercentView.swift
> +//            .opacity(isHidden ? 1 : 0)
:)

2023-07-16 07:26 UTC, cws653 commented on Projects/Home/Targets/HomeUI/Sources/View/TestFlipView.swift
> +//        .cardFilp(isFaceUp: isFaceUp, axis: axis)
TestFlipView 자체를 업로드하면 안됐는데 업로드 해버렸네요 ㅠㅠ
삭제해서 커밋하겠습니다!

2023-07-16 07:26 UTC, cws653 commented on Projects/Home/Targets/HomeUI/Sources/View/TestFlipView.swift
> +}
삭제하겠습니다!

2023-07-16 07:26 UTC, cws653 commented on Projects/Home/Targets/HomeUI/Sources/View/AnswerPercentView.swift
> +//            .opacity(isHidden ? 1 : 0)
삭제하겠습니다!

2023-07-17 14:11 UTC, szzang-kr approved these changes

2023-07-17 14:32 UTC, sohy1018 approved these changes

2023-07-17 15:04 UTC, merged